# Generated by Django 5.1.2 on 2024-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thyroidreport',
            name='file',
        ),
        migrations.AddField(
            model_name='thyroidreport',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='prediction',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='t3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='t4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='tsh',
            field=models.FloatField(default=0),
        ),
    ]
