# Generated by Django 5.1.2 on 2024-12-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model2', '0002_remove_thyroidreport_file_thyroidreport_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thyroidreport',
            name='file_path',
        ),
        migrations.AddField(
            model_name='thyroidreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='thyroidreport',
            name='file',
            field=models.FileField(default='null', upload_to='thyroid_reports/'),
        ),
        migrations.AddField(
            model_name='thyroidreport',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_reports/'),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thyroidreport',
            name='prediction',
            field=models.CharField(max_length=255),
        ),
    ]
