# Generated by Django 5.1.2 on 2024-12-20 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctor_hospital_remove_appointment_hospital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time_slot']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('9:00 AM - 10:00 AM', '9:00 AM - 10:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('1:00 PM - 2:00 PM', '1:00 PM - 2:00 PM'), ('7:00 PM - 8:00 PM', '7:00 PM - 8:00 PM')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Home.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time_slot')},
        ),
    ]
