from django.shortcuts import render
from .utils import preprocess_input, compare_with_normal, get_recommendations
import os
import random
from django.conf import settings
import joblib
import os
import re
import pdfplumber
from django.shortcuts import render
from django.http import JsonResponse

MODEL_PATH = os.path.join(
    settings.BASE_DIR, "Model2", "T3Model", "thyroid_random_forest_model.joblib"
)
model = joblib.load(MODEL_PATH)

def predict(request):
    if request.method == "POST":
        # Extract data from the request
        user_input = {
            'age': int(request.POST.get('age')),
            'sex': request.POST.get('sex'),
            'goiter': int(request.POST.get('goiter')),
            'pregnancy': int(request.POST.get('pregnancy', 0)),
            'TSH': float(request.POST.get('TSH')),
            'T3': float(request.POST.get('T3')),
            'TT4': float(request.POST.get('TT4')),
            'T4U': float(request.POST.get('T4U')),
            'FTI': float(request.POST.get('FTI')),
            'TBG': float(request.POST.get('TBG')),
            'T4': float(request.POST.get('T4')),
        }

        # Preprocess the input and predict the condition
        features = preprocess_input(user_input)
        prediction = model.predict(features)[0]
        condition = "Hyperthyroidism" if prediction == 1 else "Hypothyroidism"

        # Compare user input with normal ranges
        comparisons = compare_with_normal(user_input)

        # Get recommendations based on the predicted condition
        recommendations = get_recommendations(user_input,condition)

        all_normal = all(details['Status'] == "Within normal range" for details in comparisons.values())

        return render(
            request,
            "result.html",
            {
                "condition": condition,
                "comparisons": comparisons,
                "recommendations": recommendations,
                "all_normal": all_normal,  # This flag will be used in the template
            },
        )

    return render(request, "predict.html")


from django.contrib.auth.decorators import login_required
import pickle
import pandas as pd
import pdfplumber
import re



from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph
from datetime import datetime
import random


def draw_gradient_text(canvas, text, x, y, font, size, start_color, end_color):
    """
    Draw gradient-colored text letter by letter.
    """
    canvas.setFont(font, size)
    text_width = canvas.stringWidth(text, font, size)
    gradient_step = [(e - s) / (len(text) - 1) for s, e in zip(start_color, end_color)]

    current_color = list(start_color)
    for i, char in enumerate(text):
        canvas.setFillColorRGB(*current_color)
        canvas.drawString(x, y, char)
        x += canvas.stringWidth(char, font, size)
        current_color = [c + step for c, step in zip(current_color, gradient_step)]


def generate_pdf(report):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    c.setLineWidth(1)

    # Page dimensions
    width, height = letter
    margin = 28.35  # 1 cm in points

    # Border
    c.setStrokeColor(colors.black)
    c.rect(margin, margin, width - 2 * margin, height - 2 * margin)

    # Gradient Title for ThyroVaidya
    title = "ThyroVaidya"
    title_x = (width - c.stringWidth(title, "Helvetica-Bold", 32)) / 2
    title_y = height - margin - 40
    draw_gradient_text(
        c,
        title,
        title_x,
        title_y,
        "Helvetica-Bold",
        32,
        start_color=(0.0, 0.0, 0.6),  # Dark blue
        end_color=(0.5, 0.7, 1.0),  # Sky blue
    )

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.black)
    c.drawCentredString(width / 2, title_y - 30, "Thyroid Disease Report Analysis Result")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width / 2, title_y - 50,
                        f"Generated by ThyroVaidya on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Patient details
    report_number = random.randint(100000, 999999)
    y_position = title_y - 80
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin + 10, y_position, f"Name: {report.name}")
    c.drawString(margin + 250, y_position, f"Report Number: {report_number}")
    y_position -= 20
    c.drawString(margin + 10, y_position, f"Gender: {'Male' if report.gender == 1 else 'Female'}")
    c.drawString(margin + 250, y_position, f"Age: {report.age}")
    y_position -= 40

    headers = ["Test Name", "Report Values", "Units", "Normal Range", "Status"]
    col_widths = [100, 100, 80, 120, 100]
    table_x = margin + 10

    # Test details: Name, input value, unit, normal range, and status logic
    tests = [
        ("T3", report.t3, "ng/dL", "70-200", "Normal" if 70 <= report.t3 <= 200 else
        "Above Normal" if report.t3 > 200 else "Below Normal"),
        ("T4", report.t4, "µg/dL", "4.5-11.5", "Normal" if 4.5 <= report.t4 <= 11.5 else
        "Above Normal" if report.t4 > 11.5 else "Below Normal"),
        ("TSH", report.tsh, "µIU/mL", "0.4-4.0", "Normal" if 0.4 <= report.tsh <= 4.0 else
        "Above Normal" if report.tsh > 4.0 else "Below Normal"),
    ]

    # Draw table headers with blue shade
    c.setFont("Helvetica-Bold", 12)
    for i, header in enumerate(headers):
        c.setFillColor(colors.lightblue)  # Blue background for headers
        c.rect(table_x + sum(col_widths[:i]), y_position, col_widths[i], 20, fill=True)
        c.setFillColor(colors.black)  # Text color
        c.drawCentredString(
            table_x + sum(col_widths[:i]) + col_widths[i] / 2, y_position + 5, header
        )

    # Move position for table rows
    y_position -= 20

    # Draw rows with test details
    for test_name, report_value, unit, normal_range, status in tests:
        c.setFont("Helvetica", 12)
        for i, value in enumerate([test_name, report_value, unit, normal_range, status]):
            # Shade rows alternately for better readability
            c.setFillColor(colors.whitesmoke if i % 2 == 0 else colors.white)
            c.rect(table_x + sum(col_widths[:i]), y_position, col_widths[i], 20, fill=True)
            c.setFillColor(colors.black)
            c.drawCentredString(
                table_x + sum(col_widths[:i]) + col_widths[i] / 2, y_position + 5, str(value)
            )
        y_position -= 20

    # Add spacing after the table
    y_position -= 10

    # Prediction result
    # Set font and color for the prediction result
    c.setFont("Helvetica-Bold", 12)

    # Apply color based on the prediction result with professional medical tones
    if report.prediction == "Normal":
        c.setFillColor(colors.green)  # Green for Normal
    elif report.prediction == "Hyperthyroidism":
        c.setFillColor(colors.red)  # Red for Hyperthyroidism
    elif report.prediction == "Primary Hypothyroidism" or report.prediction == "Secondary Hypothyroidism":
        c.setFillColor(colors.orange)  # Orange for Hypothyroidism
    elif report.prediction == "Subclinical Hyperthyroidism":
        c.setFillColor(colors.yellow)  # Yellow for Subclinical Hyperthyroidism
    else:
        c.setFillColor(colors.black)  # Default black if no match

    # Draw the prediction result text in bold with the applied color
    c.drawString(margin + 1, y_position, f"Your Thyroid Test Result: {report.prediction}")

    # Explanation text dictionary for medical conditions
    prediction_explanation = {
        "Hyperthyroidism": (
            "Your thyroid test shows that you have been diagnosed with **Hyperthyroidism**, which means your thyroid is working a little too fast. "
            "This condition can sometimes cause symptoms like feeling anxious, losing weight unexpectedly, or having a faster heartbeat. "
            "While it might seem concerning, with the right treatment, your thyroid function can be brought back to normal. "
            "Common causes of hyperthyroidism include conditions like Graves' disease or thyroid nodules. "
            "Treatment options may involve medications to control thyroid hormone levels or, in some cases, iodine therapy to slow the thyroid’s activity. "
            "It’s important to consult with your doctor to determine the best course of action and follow up with the necessary treatments."
        ),
        "Normal": (
            "Your thyroid results are **Normal**, which means your thyroid is functioning properly and producing the right amount of hormones. "
            "This is great news, as it indicates that your thyroid is working optimally. "
            "When thyroid function is normal, the body’s metabolism is in balance, and symptoms like fatigue, weight gain, or hair loss are not present. "
            "Even though your thyroid is healthy now, it’s recommended to keep monitoring it regularly through check-ups to ensure continued good health."
        ),
        "Primary Hypothyroidism": (
            "Your thyroid test shows that you have **Primary Hypothyroidism**, which means your thyroid isn’t producing enough thyroid hormones. "
            "This condition can cause symptoms such as fatigue, weight gain, sensitivity to cold, and dry skin. "
            "Primary hypothyroidism is often caused by autoimmune diseases like Hashimoto's thyroiditis, where the immune system mistakenly attacks the thyroid gland. "
            "This condition is typically treated with daily thyroid hormone replacement therapy, which restores normal thyroid function and helps alleviate symptoms. "
            "With proper treatment, most individuals with hypothyroidism can live a normal, healthy life."
        ),
        "Secondary Hypothyroidism": (
            "You have been diagnosed with **Secondary Hypothyroidism**, which means the problem lies with the pituitary gland, not the thyroid itself. "
            "The pituitary gland is responsible for sending signals to the thyroid to produce hormones, and when it doesn’t work properly, thyroid hormone levels decrease. "
            "Symptoms of secondary hypothyroidism can be similar to primary hypothyroidism, including fatigue, weight gain, and cold sensitivity. "
            "Treatment usually involves thyroid hormone replacement therapy, but your doctor may also need to address any issues with the pituitary gland."
        ),
        "Subclinical Hyperthyroidism": (
            "Your results show **Subclinical Hyperthyroidism**, which means your thyroid hormone levels are slightly elevated, but you may not yet show obvious symptoms. "
            "In many cases, this doesn’t cause noticeable health issues, but it’s still important to monitor to make sure it doesn’t progress. "
            "Subclinical hyperthyroidism can sometimes occur due to minor thyroid imbalances or as a side effect of medication. "
            "If left unchecked, it can develop into more severe hyperthyroidism, so it's important to follow your doctor’s advice and keep monitoring your condition."
        ),
        "Subclinical Hypothyroidism": (
            "You have **Subclinical Hypothyroidism**, which means your thyroid function is slightly underactive, but you may not experience any noticeable symptoms. "
            "This condition is often detected through blood tests before more obvious symptoms like fatigue or weight gain occur. "
            "While it may not need immediate treatment, it’s important to monitor thyroid levels regularly to ensure it doesn’t progress into full-blown hypothyroidism. "
            "In some cases, lifestyle changes or medications may be recommended to prevent any further issues."
        )
    }

    # Explanation text to be displayed
    explanation_text = prediction_explanation.get(report.prediction, "No explanation available for this result.")

    # Define the text style for the explanation paragraph
    text_style = getSampleStyleSheet()['Normal']
    text_style.fontName = 'Helvetica'
    text_style.fontSize = 12
    text_style.leading = 14
    text_style.spaceBefore = 100
    text_style.spaceAfter = 10
    text_style.alignment = 4
    text_style.leftIndent = 3
    text_style.rightIndent = 3

    # Create a paragraph with the explanation text
    explanation_paragraph = Paragraph(explanation_text, style=text_style)

    # Calculate the available width for the paragraph
    explanation_paragraph_width = width - 2 * margin - 4  # Full width minus margins and indent

    # Wrap the paragraph text to fit the page width
    explanation_paragraph.wrap(explanation_paragraph_width, height)

    # Define top margin for the explanation
    top_margin = 320

    # Draw the explanation paragraph on the canvas, adjusted for the top margin and paragraph height
    explanation_paragraph.drawOn(c, margin, height - top_margin - explanation_paragraph.height)

    # Move to the next section (adjust y-position)
    y_position -= 100  # Adjust for the space needed after the explanation text

    recommendation = get_recommendations(report, report.prediction)
    print("My data 2025", recommendation)

    y_position -= 40
    recommendations = [
        ("Diet Recommendations:", recommendation['Diet'][:5]),
        ("Exercise Recommendations:", recommendation['Exercises'][:5]),
    ]

    for title, content in recommendations:
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(colors.black)
        c.drawString(margin + 10, y_position, title)
        y_position -= 20

        c.setFont("Helvetica", 12)
        for line in content:
            c.drawString(margin + 20, y_position, line)
            y_position -= 20

        y_position -= 10

    footer_text = (
        "Disclaimer: This report is generated using AI predictions. Consult a healthcare professional for accurate diagnosis."
    )
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawString(margin + 10, margin + 10, footer_text)

# Save PDF
    c.save()
    buffer.seek(0)
    return buffer

def extract_data_from_pdf(pdf_file):
    name, age, gender, t3, t4, tsh = None, None, None, None, None, None
    with pdfplumber.open(pdf_file) as pdf:
        pdf_text = ""
        for page in pdf.pages:
            pdf_text += page.extract_text()

        name_match = re.search(r"Name\s*[:\-]?\s*(.*?)(?=\s*Age)", pdf_text)
        if name_match:
            name = name_match.group(1).strip()

        age_match = re.search(r"Age\s*[:\-]?\s*(\d+)", pdf_text)
        if age_match:
            age = int(age_match.group(1).strip())

        gender_match = re.search(r"Gender\s*[:\-]?\s*(\w+)", pdf_text)
        if gender_match:
            gender = gender_match.group(1).strip()

        t3_match = re.search(r"T3\s+(\d+(\.\d+)?)", pdf_text)
        if t3_match:
            t3 = float(t3_match.group(1).strip())

        t4_match = re.search(r"T4\s+(\d+(\.\d+)?)", pdf_text)
        if t4_match:
            t4 = float(t4_match.group(1).strip())

        tsh_match = re.search(r"TSH\s+(\d+(\.\d+)?)", pdf_text)
        if tsh_match:
            tsh = float(tsh_match.group(1).strip())

    return name, age, gender, t3, t4, tsh

@login_required
def upload_and_predict(request):
    if request.method == "POST" and "pdf_file" in request.FILES:
        pdf_file = request.FILES.get("pdf_file")

        if not pdf_file.name.endswith(".pdf"):
            return render(request, "upload.html", {"error": "Invalid file. Only PDF files are accepted."})

        name, age, gender, t3, t4, tsh = extract_data_from_pdf(pdf_file)
        gender_numeric = 1 if gender.lower() == "male" else 0

        # Load the machine learning model
        model_path = os.path.join(settings.BASE_DIR, "Model2", "T3Model", "ThyroidpdfReader.pkl")
        with open(model_path, "rb") as f:
            model = pickle.load(f)

        # Prepare the input data
        input_data = pd.DataFrame({"T3": [t3], "T4": [t4], "TSH": [tsh], "Age": [age], "Gender": [gender_numeric]})
        prediction = model.predict(input_data)[0]

        # Save the report in the database
        report = ThyroidReport.objects.create(
            user=request.user,
            file=pdf_file,
            name=name,
            age=age,
            gender=gender_numeric,
            t3=t3,
            t4=t4,
            tsh=tsh,
            prediction=str(prediction),
        )


        pdf_buffer = generate_pdf(report)
        output_dir = os.path.join(settings.MEDIA_ROOT, "generated_reports")
        os.makedirs(output_dir, exist_ok=True)
        pdf_path = os.path.join(output_dir, f"report_{report.id}.pdf")

        with open(pdf_path, "wb") as pdf_file:
            pdf_file.write(pdf_buffer.getvalue())

        report.generated_pdf.name = f"generated_reports/report_{report.id}.pdf"
        report.save()

        # Add the URL to download the generated PDF
        pdf_url = f"/download_report/{report.id}/"

        return render(request, "upload.html", {"step": "result", "report": report, "pdf_url": pdf_url})

    return render(request, "upload.html", {"step": "upload"})

from django.shortcuts import render, redirect, get_object_or_404
from django.http import FileResponse, Http404
from django.contrib.auth.decorators import login_required
import os

@login_required
def download_report(request, report_id):
    """
    Serve the generated report PDF for download.
    """
    # Fetch the report for the logged-in user
    report = get_object_or_404(ThyroidReport, id=report_id, user=request.user)

    # Construct the file path for the generated PDF
    file_path = os.path.join(settings.MEDIA_ROOT, report.generated_pdf.name)

    # Check if the file exists
    if os.path.exists(file_path):
        # Serve the file as a response
        return FileResponse(open(file_path, "rb"), as_attachment=True, filename=f"Thyroid_Report_{report.name}.pdf")
    else:
        # If file is missing, return an error page
        raise Http404("The requested file does not exist.")

import os
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ThyroidReport
from datetime import datetime


@login_required
def profile_page(request):
    # Fetch all reports for the logged-in user
    reports = ThyroidReport.objects.filter(user=request.user)

    # Add the last modified date of the generated PDF to each report
    for report in reports:
        if report.generated_pdf:
            file_path = report.generated_pdf.path
            # Get last modified time of the PDF file (Unix timestamp)
            if os.path.exists(file_path):
                report.pdf_generated_date = datetime.fromtimestamp(os.path.getmtime(file_path)).strftime(
                    '%Y-%m-%d %H:%M:%S')
            else:
                report.pdf_generated_date = "Unknown"
        else:
            report.pdf_generated_date = "No PDF available"

    return render(request, "profile.html", {"reports": reports})


@login_required
def download_pdf(request, report_id):
    # Fetch the report for the logged-in user
    report = get_object_or_404(ThyroidReport, id=report_id, user=request.user)

    # Construct the file path for the generated PDF
    file_path = report.generated_pdf.path if report.generated_pdf else None

    # Serve the file if it exists
    if file_path and os.path.exists(file_path):
        return FileResponse(open(file_path, "rb"), as_attachment=True, filename=f"Thyroid_Report_{report.name}.pdf")
    else:
        raise Http404("The requested PDF does not exist.")


import os
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import ThyroidReport

@login_required
def delete_report(request, report_id):
    # Get the report for the logged-in user
    report = get_object_or_404(ThyroidReport, id=report_id, user=request.user)

    # Delete the associated files from the filesystem
    if report.file and os.path.isfile(report.file.path):
        os.remove(report.file.path)
    if report.generated_pdf and os.path.isfile(report.generated_pdf.path):
        os.remove(report.generated_pdf.path)

    # Delete the report from the database
    report.delete()

    return redirect('profile_page')  # Redirect to the profile page

def reportanalysis(request):
    return render(request,"report_analysis.html")
